version: '3.3'

services:

 traefik:
  image: traefik
  command:
   - "--web"
   - "--docker"
   - "--docker.swarmmode"  
   - "docker.domain=dexter.com.br"
   - "defaultentrypoints=http"
  ports:
   - target: 80
     published: 80
     protocol: tcp
   - 8080:8080
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  deploy:
   placement:
    constraints:
     - node.role == manager

 site:
  image: rodoxxx/site3:v1
  #ports:
  # - 8080:80
  depends_on:
   - redis
  deploy:
   labels:
    - "traefik.port=80"
    - "traefik.backend.healthcheck.port=80"
    - "traefik.frontend.rule=Host:rodolfo.dexter.com.br"
    - "traefik.backend.healthcheck.interval=2s"
   replicas: 5
   resources:
    limits:
     cpus: '0.5'
     memory: '350M'
    reservations:
     cpus: '0.1'
     memory: '100M'
  volumes:
   - teste:/usr/local/apache2/htdocs/

 redis:
  image: redis
  deploy:
   replicas: 1
   placement:
    constraints:
     - node.role == manager

volumes:
 teste:
